config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users
  resources :user_posts do 
    resources :comments
  end 
  get '/u/:id', to: "users#profile"
  root 'pages#home'
  get 'about',to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :rooms do
    resources :messages
  end
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :set_user_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /user_posts or /user_posts.json
  def index
    @user_posts = UserPost.all.order(created_at: :desc)
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
    @user_post.update(view: @user_post.view + 1)
    @comments=@user_post.comments.order(created_at: :desc)
  end

  # GET /user_posts/new
  def new
    @user_post = UserPost.new
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = UserPost.new(user_post_params)
    @user_post.user = current_user

    respond_to do |format|
      if @user_post.save
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.require(:user_post).permit(:title, :body)
    end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/_form.html.erb
<%= form_with(model: user_post) do |form| %>
  <% if user_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_post.errors.count, "error") %> prohibited this user_post from being saved:</h2>

      <ul>
        <% user_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_posts/_user_post.html.erb
<div id="<%= dom_id user_post %>">
  <p>
    <strong>Title:</strong>
    <%= user_post.title %>
    <h4>Posted by <%= user_post.user.email %></h4>
  </p>
                              
  <p>
    <strong>Body:</strong>
    <%= user_post.body %>
  </p>

    <p>
    <strong>Views:</strong>
    <%= pluralize(user_post.view,"view") %>
  </p>
</div>

app/views/user_posts/edit.html.erb
<h1>Editing user post</h1>

<%= render "form", user_post: @user_post %>

<br>

<div>
  <%= link_to "Show this user post", @user_post %> |
  <%= link_to "Back to user posts", user_posts_path %>
</div>

app/views/user_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User posts</h1>

<div id="user_posts">
  <% @user_posts.each do |user_post| %>
    <%= render user_post %>
    <p>
      <%= link_to "Show this user post", user_post %>
    </p>
  <% end %>
</div>

<%= link_to "New user post", new_user_post_path %>

app/views/user_posts/new.html.erb
<h1>New user post</h1>

<%= render "form", user_post: @user_post %>

<br>

<div>
  <%= link_to "Back to user posts", user_posts_path %>
</div>

app/views/user_posts/show.html.erb
<%= render @user_post %>

<div>
  <%= link_to "Edit this user post", edit_user_post_path(@user_post) %> |
  <%= link_to "Back to user posts", user_posts_path %>

  <%= button_to "Destroy this user post", @user_post, method: :delete %>
</div><br>
 
 <h4>Comments</h4>
<div class="container">
  <%= render "comments/form" , user_post: @user_post, comment: @user_post.comments.build , submit_label: "Reply"%>
  <% @comments.each do |comment|%>
    <%= render "comments/comment" , user_post: @user_post, comment: comment%>
  <% end %>
</div>