config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users
  resources :user_posts do 
    resources :comments
  end 
  get '/u/:id', to: "users#profile"
  root 'pages#home'
  get 'about',to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :user_post
  has_rich_text :body
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  before_create :confirm_participant

def confirm_participant
  if self.room.is_private
     is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
     throw :abort unless is_participant
  end
end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_room , ->{where(is_private: false)}
  after_create_commit {broadcast_append_to "rooms"}
  has_many :messages

  has_many :participants, dependent: :destroy
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
        
   has_many :user_posts  
   has_many :comments    

   scope :all_except ,->(user){where.not(id: user)}
  #  after_create_commit {broadcast_append_to "users"}
   has_many :messages


   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name 
    end
  end

end

app/models/user_post.rb
class UserPost < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @user_post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_post_path(@user_post), notice: 'Comment has been created'
    else
      redirect_to user_post_path(@user_post), alert: 'Comment has not been created'
    end
  end

  def destroy
    @comment = @user_post.comments.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@user_post)
  end

  def update
    @comment = @user_post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to user_post_url(@user_post), notice: 'Comment has been updated' }
      else
        format.html { redirect_to user_post_url(@user_post), alert: 'Comment was not updated!' }
      end
    end
  end

  private

  def set_post
    @user_post = UserPost.find(params[:user_post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end
  private
  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @room = Room.new
    @rooms=Room.public_room
    @users=User.all_except(current_user)
    
  end

  def show 
    @single_room= Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_room
    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(name: params['room']['name'])
  end
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :set_user_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /user_posts or /user_posts.json
  def index
    @user_posts = UserPost.all.order(created_at: :desc)
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
    @user_post.update(view: @user_post.view + 1)
    @comments=@user_post.comments.order(created_at: :desc)
  end

  # GET /user_posts/new
  def new
    @user_post = UserPost.new
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = UserPost.new(user_post_params)
    @user_post.user = current_user

    respond_to do |format|
      if @user_post.save
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_to user_post_url(@user_post), notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.require(:user_post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user 

  def profile
    @user.update(views: @user.views+1)
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @rooms = Room.public_room
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages

    render "rooms/index"
  end

  private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
  
   def set_user
    @user=User.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_flash.html.erb
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <div>
  <%= flash %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/about">Rails Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
            <%= link_to "Blog" ,  user_posts_path ,  class:"nav-link active"%>
        </li>
        <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="/about">About</a>
        </li>
      </ul> 
    </div>
    <ul>
    <%= render "user/session_manager"%>
    </ul>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex') do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class:'d-flex') do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullProject19</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
        justify-content: flex-end
      }
    </style>
  </head>

  <body>
  <header>

<% if flash[:notice].present? %>
<%= render "layouts/flash" ,flash: flash[:notice] %>
<% end %>
   <%= render "layouts/navbar"%>
  </header>
  <div class= "container">
  <main>
    <%= yield %>
  </main>
  </body>
  </div>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Home" ,root_path %>

app/views/pages/home.html.erb
<div class="container">
  <h1>This is Home Page</h1>
  <p>let me know about , the rails !!!</p>
  <%= link_to "About me ",about_path, class:"btn btn-secondary" %> 
  <%= link_to "Blog" ,  user_posts_path , class:"btn btn-primary" %>
  <%= link_to "Start Chatting With your Friends " ,rooms_path, class:"btn btn-info" %>
</div>